<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:14:45.
 */
class colorboxJsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var colorboxJs
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new colorboxJs;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers colorboxJs::getInstanceOf
     * @todo   Implement testGetInstanceOf().
     */
    public function testGetInstanceOf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers colorboxJs::init
     * @todo   Implement testInit().
     */
    public function testInit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers colorboxJs::formDialogWithData
     * @todo   Implement testFormDialogWithData().
     */
    public function testFormDialogWithData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers colorboxJs::formDialog
     * @todo   Implement testFormDialog().
     */
    public function testFormDialog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers colorboxJs::ajaxDialog
     * @todo   Implement testAjaxDialog().
     */
    public function testAjaxDialog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
